# Generated by Django 4.1 on 2022-08-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('weight', models.FloatField(max_length=32)),
                ('height', models.FloatField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('behaviour', models.CharField(max_length=128)),
                ('nutrition', models.CharField(choices=[('car', 'carnivore'), ('omn', 'omnivore'), ('hrv', 'herbivore')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField(editable=False)),
                ('race', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('prt', 'Parrot'), ('fsh', 'Fish')], max_length=3)),
                ('detailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalShop.animaldetail')),
            ],
        ),
    ]
