# Generated by Django 3.2.15 on 2022-08-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(),
        ),
    ]
